# Alembic Config
[alembic]
# path to migration scripts (created app/alembic)
script_location = app/alembic
prepend_sys_path = .
version_locations = %(here)s/app/alembic/versions
version_path_separator = os

# DB connection from env
; sqlalchemy.url = %(DATABASE_URL)s
# Inside alembic.ini
sqlalchemy.url = postgresql+psycopg2://kyrgyz:kyrgyz_password@db:5432/kyrgyz_ai
[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S

